Renamed option "--map-args" to "--map".
Added option "--metadata".

Options "--map", "--metadata" and "--misc-args" now no longer require single quoting.

diff --git a/h265 b/h265
--- a/h265
+++ b/h265
@@ -8,7 +8,8 @@
 usage() {
 	echo 'Usage:'
 	echo "$0
-	--map-args <stream mapping options> (default: -map 0) (please pass them in single quotes)
+	--map <stream specifier>+ (default: 0)
+    --metadata (<stream specifier>? <key>=<value>)+
 	--opus [bitrate]
 	--downmix-stereo
 	--outdir <output directory> (default: ./reencode)
@@ -16,13 +17,13 @@ usage() {
 	--720p | --1080p
 	--quality <CRF> (default: 20)
 	--sharpen
-	--misc-args <arbitrary ffmpeg arguments> (please pass them in single quotes)
+	--misc-args <arbitrary ffmpeg arguments>
 	--dry-run"
 }
 
-# convenciency function printing an error message when an options requries a non-empty argument following but there isn't one
+# convenciency function printing an error message when an option requires a non-empty argument following but there isn't one
 missing_arg_error() {
-	printf 'ERROR: "%s" requires a non-empty option argument.\n' "$1" >&2
+	printf 'ERROR: missing argument for "%s".\n' "$1" >&2
 }
 
 # conveniency function printing an error message when two incompatible options have been passed together
@@ -84,28 +85,50 @@ while [[ -n "$1" ]]; do
 		usage
 		exit
 		;;
-	--map-args)
+	--map)
 	# set stream mapping
-		if [[ -n "$2" ]]; then
-			# mind the lack of quotes for $2: Bash is a special boy when strings start with -
-			mapargs=( $2 )
-			shift
-		else
-			missing_arg_error '--map-args'
-			exit 1
-		fi
-		;;
+        mapargs=( )
+        while [[ -n "$2" ]] && [[ "$2" != --* ]]; do
+            mapargs+=('-map' "$2")
+            shift
+        done
+        if [[ "${mapargs}" == "" ]]; then
+            missing_arg_error '--map'
+            exit 1
+        fi
+        ;;
+	--metadata)
+    # set metadata tags
+        if [[ -z "$2" ]] || [[ "$2" == --* ]]; then
+            missing_arg_error '--metadata'
+            exit 1
+        fi
+        while [[ -n "$2" ]] && [[ "$2" != --* ]]; do
+            if [[ "$2" == *=* ]]; then
+                metadataargs+=("-metadata" "$2")
+                shift
+            else
+                if [[ -z "$3" ]] || [[ "$3" != *=* ]]; then
+                    missing_arg_error '--metadata'
+                    exit 1
+                fi
+                metadataargs+=("-metadata:$2" "$3")
+                shift 2
+            fi
+        done
+        ;;
 	--misc-args)
 	# arbitrary arguments
-		if [[ -n "$2" ]]; then
-		# likewise lack of quotes, see above
-			miscargs=( $2 )
-			shift
-		else
-			missing_arg_error '--misc-args'
-			exit 1
-		fi
-		;;
+        miscargs=( )
+        while [[ -n "$2" ]] && [[ "$2" != --* ]]; do
+            miscargs+=( "$2" )
+            shift
+        done
+        if [[ "${miscargs}" == "" ]]; then
+            missing_arg_error '--misc-args'
+            exit 1
+        fi
+        ;;
 	--opus)
 	# set audio conversion to Opus
 		audiocodec=('libopus' '-vbr' 'on' '-compression_level' '10' '-b:a')
